version: "3"

services:
  sftp:
    image: atmoz/sftp:alpine
    container_name: sftp
    restart: always
    volumes:
      - ./sftp/users.conf:/etc/sftp/users.conf:ro # users
      - /storage/ftp/hippoline:/home/hippoline    # hippoline
      - ./sftp/keys/hippoline.pub:/home/hippoline/.ssh/keys/hippoline.pub:ro # hippoline ssh
    ports:
      - "2244:22"
  
  # zie https://hub.docker.com/r/atmoz/sftp