version: "3"

services:
  sftp:
    image: atmoz/sftp:alpine
    container_name: sftp
    restart: always
    volumes:
      - ./sftp/users.conf:/etc/sftp/users.conf:ro                               # users
      - ./ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key                    # private key
      - ./ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key                            # private key
      - /storage/ftp/hippoline:/home/hippoline                                  # hippoline
      - ./sftp/keys/hippoline.pub:/home/hippoline/.ssh/keys/hippoline.pub:ro # hippoline ssh
    ports:
      - "2244:22"
  
  # zie https://hub.docker.com/r/atmoz/sftp